---
title: "Mini Proyecto TD 2024"
subtitle: "Entrega parcial"
author: |
  Víctor Álvarez Palomares,  
  Belén Gallego Andreu,  
  Sergio Martínez Yagüe,  
  Ferran Medina Mompó,  
  Carles Pascual i Sivera,  
  y Úrsula Casaus Fabra
date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introducción

```{r}

```

## Importación de los datos

```{r}
# Para extraer los datos de los ficheros .pdf, hay que pasarlos a .txt:

# Esta función separa los productos de los tickets en tres columnas, unidades, 
# producto y precio.
library(pacman)
p_load(dplyr, stringr)


separar <- function(a) {
  a <- iconv(a, to = "UTF-8") # Esta línea hace que no de error al leer 
  # caracteres especiales
  productos<-a[8:(length(a)-13)] # Seleccionamos solo las filas con productos y 
  # creamos un dataframe
  df<-data.frame(producto=productos )
  df <- df %>%
  mutate(unidades = as.numeric(str_extract(producto, "\\d+"))) %>% # Seleccionamos
    # el número de unidades y hacemos una columna
  mutate(precio = (substr(producto, nchar(producto) - 3, nchar(producto))), 
         # Seleccionamos el precio y hacemos una columna
         producto = sub("^\\d+", "", producto)) # Borramos las unidades de la 
  # columna original
  return(df)
}


a <- readLines("./data/20231218 Mercadona 60,47 Ôé¼.txt")
b <- readLines("./data/20231224 Mercadona 37,49 Ôé¼.txt")
c <- readLines("./data/20231226 Mercadona 25,83 Ôé¼.txt")
d <- readLines("./data/20231230 Mercadona 66,30 Ôé¼.txt")
e <- readLines("./data/20240102 Mercadona 70,04 Ôé¼.txt")
f <- readLines("./data/20240108 Mercadona 83,73 Ôé¼.txt")
g <- readLines("./data/20240109 Mercadona 7,35 Ôé¼.txt")


separar(a)
separar(b)
separar(c)
separar(d)
separar(e)
separar(f)
separar(g)

# Cuando hay algún caracter especial como \ o -, sustituye esa fila por NAs, además 
# no funciona para las frutas porque estan en otro formato distinto.
# También falta borrar el precio de la columna productos.
```

